fix(ci-cd): fix build error caused by missing dep #38
error: `ModuleNotFoundError: No module named 'psycopg2'`
fix: add `psycopg2-binary` to requirements.txt
additionally: fix test migration by adding index drop to up script