fix(ci-cd): fix build error caused by missing dep and migrations #38
error: `ModuleNotFoundError: No module named 'psycopg2'`
fix: add `psycopg2-binary` to requirements.txt
additionally: fix migration scripts by adding index drop to up paths